apiVersion: v1
kind: Service
metadata:
  name: python-server-svc
spec:
  selector:
    app: pythonserver
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 1234
      targetPort: 8080
      nodePort: 32200
