apiVersion: apps/v1
kind: Deployment
metadata:
  name: logoutput
spec:
  selector:
    matchLabels:
      app: log-output
  replicas: 1
  template:
    metadata:
      labels:
        app: log-output
    spec:
      containers:
        - name: log-output
          image: hditano/log_output:latest
