from http.server import HTTPServer, BaseHTTPRequestHandler
import uuid
import requests
import random

print("Starting Server...")

# Creating a UUID that will live with the process

process_uuid = uuid.uuid4()
external_url = "https://restcountries.com/v3.1/name/"
random_country = ["Argentina", "Brazil", "Italy", "Germany", "Poland", "Ireland"]


class SimpleHTTPRequestHandler(BaseHTTPRequestHandler):
    def do_GET(self):
        self.send_response(200)
        self.end_headers()
        response_uuid_message = (
            f"UUID Generated for Request: {uuid.uuid4()}\n"
            f"UUID Generated by Process: {process_uuid}"
        )
        self.wfile.write(response_uuid_message.encode())
        self.ExternalRequestCall()

    def ExternalRequestCall(self):
        print("Calling External Request..")
        random_c = random.choice(random_country)
        result = requests.get(external_url + f"{random_c}")
        for item in result.json():
            name = item.get("name")
            official = name.get("official")
            print(official)


httpd = HTTPServer(("", 8000), SimpleHTTPRequestHandler)
httpd.serve_forever()
